server : server.cpp user.cpp
	g++ -o server.o -I includes/polarssl -L./library/ server.cpp -lpolarssl

client: client.cpp utility.cpp
	g++ -o client.o -I includes/polarssl -L./library/ client.cpp -lpolarssl


